name: Pull request CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        
        - name: Setup pnpm
          uses: pnpm/action-setup@v3
          with:
            version: 10
        - name: Install dependecies
          run: pnpm i
        - name: Run type check
          run: pnpm run type:check
        - name: Run Linter
          run: pnpm run lint

  Run-Unit-Tests:
    runs-on: ubuntu-latest
    needs: [Lint]
    steps:
        - uses: actions/checkout@v4
        
        - name: Setup pnpm
          uses: pnpm/action-setup@v3
          with:
            version: 10
        - name: Install dependecies
          run: pnpm i
        - name: Run Tests
          run: pnpm test -t 'Unit'

  Run-Integration-Tests:
    runs-on: ubuntu-latest
    needs: [Lint]
    steps:
        - uses: actions/checkout@v4
        
        - name: Setup pnpm
          uses: pnpm/action-setup@v3
          with:
            version: 10
        - name: Install dependecies
          run: pnpm i
        - name: Run Tests
          run: pnpm test -t 'Unit'
